### ISSUE TITLE
What am I doing wrong? [question]

### ISSUE THREAD

**Issue by souzajr** [expressjs/cookie-session#114]
Hello! I used the following cookie configuration:

`app.use(cookieSession({
        name: 'session',
        keys: [process.env.SESSION_SECRET1, process.env.SESSION_SECRET2],
        path: '/',
        httpOnly: true,
        secure: false,
        maxAge: 3600000,
    }))`

When I look at the cookie in the browser, it looks like this:

`eyJ1c2VyIjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBaQ0k2SWpWak1qWmhaR0prWXpWaVkyWXlNMkZtT0RJeU1EWmhNeUlzSW1WdFlXbHNJam9pY205aVpYSjBiM011WTNCelFHZHRZV2xzTG1OdmJTSXNJbWx6Y3lJNkltaDBkSEE2THk5c2IyTmhiR2h2YzNRNk16QXdNQ0lzSW1saGRDSTZNVFUwTmpJeE1UY3dPU3dpWlhod0lqb3hOVFEyTWprNE1UQTVmUS5kQmppZTZCbEt0dnFHR0ZmNGxqUHdhWFkxWkplQXRzNDBZbGViWHRsQWpRIn0=`

When I copy this code above and paste it into[ JWT.io](https://jwt.io/), for example, it shows me all the contents of the cookie. My question is: why use the security keys if all cookie content is open?

**Comment by dougwilson** [comment]
The keys are only used to sign the contents (from the documentation for keys option https://github.com/expressjs/cookie-session/blob/master/README.md#keys), not encrypt the contents. There is no option to encrypt the contents built in, currently. 

If you would like the data encrypted,  there are three options currently:

1. Use a server side session to store the contents on the server instead of the client. 
2. Encrypt the data and set cipher text in req.swssion
3. Make a pull request to add an encryption feature :)

I hope this helps.
