### ISSUE TITLE
Generating unique session.sig after logout/login

### ISSUE THREAD

**Issue by mshibl** [expressjs/cookie-session#116]
I realized that after logging out and destroying the session -- when the user logs back in the same exact **session.sig** is generated once again. 

The issue here is that by keeping a copy of the **session** and **session.sig**  I was able to make authenticated requests to the server -- even after the user has logged out. Is this intended? Am I doing something wrong?

Is there a way we can make sure a new unique **session.sig** is generated on every new login -- and how can we insure that the old session.sig becomes invalid?

**Comment by dougwilson** [comment]
So the sig is just a hash of the data itself. Since the client controls all the data, it can always resend the data even after uou alter it from the server, because ultimately the client controls it. This is the downside of client side sessions.

You may want to consider using server side sessions instead, where the client cannot control what data is sent back, as that is ultimately the only way to you can expire a session based on an event instead of time: you have to have something stored on the server to know if that given session has been logged out or not.

I hope this helps explain the difference between client side and server side sessions.

I you know a way in which to implement this without any server side storage, you're welcome to open a pull request with an implementation. As far as I know, it is not possible to prevent what you described with client side sessions.

**Comment by mshibl** [comment]
Just to make sure I understand -- there's no way to ever invalidate that cookie session once created? does it become invalid once it expires?

**Comment by dougwilson** [comment]
Yes, that is correct. You can always add a date time in your data you store which is the time you want to expire the session, but the session will then be valid until that time passes, so the log out scenario would still not work since you wouldn't know the exact date time the user will log out ahead of time.
