### ISSUE TITLE
Can't disable sessions for other strategies

### ISSUE THREAD

**Issue by newmanw** [expressjs/cookie-session#120]
I have a short lived session setup for a few routes.  Once I am done with the session I call:

```
req.logout();
req.session = null;
```

I have routes setup to use a different passport strategy that doesn't require a session.  However when I access those routes it looks like cookie-session is setup again as I am getting a new session cookie in the response.

Best guess is that once the cookie expires on the client this code thinks the session has changed and it re-initializes it?

https://github.com/expressjs/cookie-session/blob/43515de8ae9d5e6d56e15da6c641c5d3696b3a28/index.js#L175-L188

Is this intended?  Anyway to disable cookie-session when I am done with it?

**Comment by dougwilson** [comment]
Hi @newmanw ! If you set `req.session = null` the only reason the cookie would come back if if you add something back into `req.session` again. Can you show a complete demonstration of the issue, so I can reproduce it to see what the issue is? The snippet you showed at the top is how you delete the session.

But also maybe I'm misunderstanding your issue as well, so some complete code that reproduces the issue that I can run and look at would likely really help us get to a common understanding, and if there is a bug in this module, I'll have something to debug to get a fix created for you 👍

**Comment by dougwilson** [comment]
Closing due to no response.
