### ISSUE TITLE
Why is the session user undefined inside the websocket upgrade handler?

### ISSUE THREAD

**Issue by slidenerd** [expressjs/cookie-session#160]
- First of all, thank you for the wonderful work you have put in maintaining this library.
- I am using ws for websocket and cookie-session to manage sessions for passport-local login
- I am not able to retrieve the logged in user inside the websocket session.
- [Here is  the minimum reproducible example where the user is undefined](https://pastebin.com/SWfa4Qum)

The only other issue I have found related to websockets is #117 and the solution there which mentions
```
const cookies = new Cookies(req, null, { keys })
const session = JSON.parse(Buffer.from(cookies.get('session'), 'base64').toString('utf8'))
```
gives an error when you put it inside  the upgrade handler

**Comment by dougwilson** [comment]
Thank you for this repo. Please provide instructions for how to reproduce the issue though; `req.session` is `undefined` if you don't send the `cookie` request header with the cookie data. The instructions just say to "make a request", but exactly how you are doing that is needed to answer your question.

**Comment by slidenerd** [comment]
I am sorry, my comments in code mentioned how to reproduce the issue but I ll paste here again
```
1) Open postman, Do a POST request to http://localhost:3000/login with "email": "test@example.com" and "password":"123456789", it will be successful and create a session for the logged in user
2) Do a GET request to http://localhost:3000/user to get the logged in user and it should work
3) Open a websocket request to ws://localhost:3000 and send an {"event": "message"}
4) Notice the console. the session and its user or user id is all undefined or empty.
```

**Comment by dougwilson** [comment]
Thanks, I did see that, but how are you managing the cookies in that? Like should I be pasting in the cookie header in postman? What about for the websocket? The issue is that your websocket request is not including the cookie, which is why `req.session` is `undefined`. The solution is to send the two cookies in the `cookie` request header. That is determined with how you are making the request itself, not an issue with this module. This module is simply relaying the state you provided in your request...
