### ISSUE TITLE
Session cookie not sent over from server when using Firefox

### ISSUE THREAD

**Issue by realmers** [expressjs/cookie-session#162]
Hello, I use cookie-session and when i look at the network tab for chrome i see the set-cookie header but this is missing in firefox. I also can't find the cookie in storage when using firefox

this is my code:
```
app.use(cookieParser({
    signed: false,
    secure: process.env.NODE_ENV !== "test",
}))
```

this is how I set cookie:
`req.session = { jwt: userJwt };`

**Comment by dougwilson** [comment]
Hello, and sorry you are having trouble. In order to assist, we need to be able to repliacte the issue. Can you either provide a conplete app with this module that demonstrates the issue or check if our example app https://github.com/expressjs/cookie-session#simple-view-counter-example replicates the issue?

**Comment by realmers** [comment]
So i tried the counter example and it worked. I currently do not have a complete app but instead an incomplete which you can find in this repository https://github.com/realmers/Ticketing. It's a microservice oriented app with NextJS as my frontend and node as backend.

Look under the auth folder for implementation of session-cookie. I expect the jwt to attach itself to req.session in signin.ts, signout.ts

**Comment by dougwilson** [comment]
Hi @realmers thank you for that. I mean, it would seem that if the counter example worked, then this module does indeed work fine with your firefox web browser. There must be something in your code that is preventing it from working. I took a look around and didn't see anything obvious, but there is _a lot_ going on in there. You said you can see the `set-cookie` header in the response, so that means that everything is indeed functional with this module -- you set the `req.session` and it turned around and set the `set-cookie` header. Why it is not getting set in your browser is not something I happen to know now after looking, unfortunately :(

You're always welcome to pull request a fix if you narrow it down!

**Comment by thasup** [comment]
@realmers I also have the same problem.

Try accessing your site using `https://` that should solve it.
