### ISSUE TITLE
wildcard subdomains

### ISSUE THREAD

**Issue by ORESoftware** [expressjs/cookie-session#53]
I saw that for express-session you could put a "wildcard" for subdomains like so:

```
   app.use(cookieSession({
        name: 'lectal-cookie',
        secret: 'Bartholomew-the-Apostle',
        domain: '.herokuapp.com'  // << with express-session you can do this
    }));
```

is this possible with cookie-session?

How can we make the cookie available for any subdomain of herokuapp.com? Or perhaps more securely for just two or three subdomains of herokuapp.com?

thanks :)

**Comment by dougwilson** [comment]
Hi @ORESoftware, those settings are just passing the values through to the `Set-Cookie` header for the web browser to interpret and handle as it is designed to do so.

The short answer to your two questions is:

> How can we make the cookie available for any subdomain of herokuapp.com?

You set `domain` to `.herokuapp.com`, assuming the web browser will even accept cookies on this domain, as they likely have this blocked due to the subdomains not having relation to each other.

> Or perhaps more securely for just two or three subdomains of herokuapp.com?

Unfortunately, this is not possible, which is a limitation of how cookies work in web browsers, not something we can really control in any way :(

**Comment by tnguyen14** [comment]
@dougwilson if it is not `herokuapp.com`, but `.mypersonalsite.com`, do you know if the browser will accept cookies for subdomains then?
