### ISSUE TITLE
how to force not to save cookies?

### ISSUE THREAD

**Issue by dinukasal** [expressjs/cookie-session#72]
How can I decidee whether to save cookies or not based on a req.body property for example remember_me checkbox?

**Comment by dougwilson** [comment]
Since this module doesn't actually set the cookie unless you add something to the session, the easiest solution is don't add anything to the session if you don't want the session to be created.

Alternatively if you added something to the session and later in the code decided you don't want the session, you can destroy it with req.session = null

**Comment by dinukasal** [comment]
@dougwilson thank you!
