### ISSUE TITLE
Where is the signing component?

### ISSUE THREAD

**Issue by RevealedFrom** [expressjs/cookie-session#80]
This is my first attempt at reading the source code of a Node.js module on Github, so please treat me gently.

Is index.js the only file containing actual code for cookie-session? I can't locate any other Javascript files (other than test.js) in the repository.

I am looking for the place where the session cookie is verified for correct signature. I searched for the string fragment "sign" and found only four instances in index.js and they are all about checking and setting  `options.sign`. Am I barking up the wrong tree?

Hope someone can show me how to fish, so that I may catch my own fish everyday. Thanks.

**Comment by dougwilson** [comment]
Hi @RevealedFrom I'm happy to help :) To clarify, there is no such thing as `options.sign` in this module. So either (1) you may have accidentally looked at the wrong module or (2) perhaps you meant something different, like our `options.signed`?

**Comment by RevealedFrom** [comment]
Sorry, it's `options.signed`.  My search string was `sign` to catch as much as possible, and I got mixed up.

I can't find anything relating to this option, other than setting it, in index.js.  What am I missing?

Thanks.

**Comment by dougwilson** [comment]
Hi @RevealedFrom the [index.js](https://github.com/expressjs/cookie-session/blob/master/index.js) is the only code file in this module. Like most npm modules, this module also uses [a few dependencies](https://github.com/expressjs/cookie-session/blob/master/index.js#L15-L17).

The code you are searching for is actually handled by a dependency of this module. Since you wanted to fish, here is how I would walk through unknown code, given one known: you know that the `sign` key in the `options` object controls the functionality you seek.

1. Find the thing that is exported (https://github.com/expressjs/cookie-session/blob/master/index.js#L24)
2. View the definition of that thing (https://github.com/expressjs/cookie-session/blob/master/index.js#L40) and note that the `options` argument is what you want to follow.
3. Find the only reference to `options` is the next line (https://github.com/expressjs/cookie-session/blob/master/index.js#L41), causing you to follow the `opts` variable now.
4. Look for either direct usages of `opts.signed` or anywhere where `opts` as a whole is passed off somethere else. For example, it is set if not already set at https://github.com/expressjs/cookie-session/blob/master/index.js#L53 , printed to debug at https://github.com/expressjs/cookie-session/blob/master/index.js#L57 , and finally copied to `req.sessionOptions` at https://github.com/expressjs/cookie-session/blob/master/index.js#L67
5. Now do the same for `req.sessionOptions`; it is passed in whole outside of this module in three places: https://github.com/expressjs/cookie-session/blob/master/index.js#L118 and https://github.com/expressjs/cookie-session/blob/master/index.js#L253 and https://github.com/expressjs/cookie-session/blob/master/index.js#L316
6. All of those are passing into an object `cookies`, which comes from https://github.com/expressjs/cookie-session/blob/master/index.js#L60-L62
7. Which leads to the conclusion that `options.signed` is pass straight through to the `.get` and `.set` APIs in the `cookies` npm module.

**Comment by RevealedFrom** [comment]
Thank you for the detailed guidance!
