### ISSUE TITLE
www.domain.exm and domain.exm different cookies

### ISSUE THREAD

**Issue by ramazan793** [expressjs/cookie-session#92]
Hi! Im new in node js and I have a weird thing. If I login with domain.exm - cookies are saving, but if I login with www.domain.exm - cookies arent saving. Is this a bug? Should I add redirect for domain.exm or change some to prevent it?

**Comment by dougwilson** [comment]
Hi @ramazan793 yes, this is how web browsers handle cookies and it would affect any cookie-based module. In order to get your cookie to work / set on both domains, you'll need to explicitly set the `domain` option to the higher domain (just `"domain.exm"`). You'll want to clear out the existing cookie from any web browsers that have it already set so it will properly set under the new parameters (web browsers will just drop cookie sets if you don't match the existing cookie properties).

I hope this helps!
