### ISSUE TITLE
Secure flag not set in Cloud Foundry

### ISSUE THREAD

**Issue by workin-bob** [expressjs/cookie-session#99]
It turns out that when using (Pivotal) Cloud Foundry, the last hop (router to instance) is not HTTPS.  I understand that it's encrypted, albeit with IPSec.

What I'm requesting is a way to force the "secure" cookie flag when the last hop is not TLS.  It might take the form of forcing it using in option (best for my scenario) or perhaps detecting an HTTP Request header (x-forwarded-proto) that gets set by a proxy (perhaps more generic).

**Comment by dougwilson** [comment]
This module will abide by the Express.js `"trust proxy"` setting (http://expressjs.com/en/4x/api.html#app.set and http://expressjs.com/en/guide/behind-proxies.html). Are you using that already? We can add a way to force override, though getting Express setup properly is the most ideal method otherwise you'll end up finding various modules that will need forced overrides to compensate.

**Comment by workin-bob** [comment]
I was not using the "trust proxy" setting.  Setting that did indeed result in the desired behavior.

While it's true I should've done this when using Express, I recommend a tweak to this library docs where the "secure" option is mentioned.

Thanks again.

**Comment by dougwilson** [comment]
What should the tweak be. Here is the current text in the readme:

> secure: a boolean indicating whether the cookie is only to be sent over HTTPS (false by default for HTTP, true by default for HTTPS). If this is set to true and Node.js is not directly over a TLS connection, be sure to read how to setup Express behind proxies or the cookie may not ever set correctly.

Where "setup Express behind proxies" is a link to https://expressjs.com/en/guide/behind-proxies.html

**Comment by workin-bob** [comment]
I wish I could blame my oversight on a long night or something, but alas...
